name: Publish to GitHub Packages

on:
  push:
    branches: [ "main"  ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci

  publish-gpr:
    name: Publish to GitHub Packages Registry
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm ci

      - name: Publish Package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHPR_TOKEN }}
